services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - target: 3306
        host_ip: 0.0.0.0
        protocol: tcp
        mode: host
    networks:
      - demo-rails-app

  demo-app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - demo-rails-app

volumes:
  mysql_data:

networks:
  demo-rails-app:
    driver: bridge